version: '3.3'

networks:
  inception_network-lu:

volumes:
  wordpress-volume-lu:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

  mariadb-volume-lu:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: requirements/mariadb
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
      - mariadb-volume-lu:/var/lib/mysql
    networks:
      - inception_network-lu

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    build: 
      context: requirements/wordpress
    volumes:
     - wordpress-volume-lu:/var/www/html
    networks:
      - inception_network-lu

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      args:
        - LOGIN
    volumes:
      - wordpress-volume-lu:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - inception_network-lu
    ports:
      - 443:443
